defmodule MLServe.Case do
  @moduledoc """
  Shared ExUnit case for MLServe's tests.

  ## Why every test gets a unique model name

  MLServe is a singleton OTP application with one global catalog, so tests share state by
  construction. Rather than serialising the suite with `async: false` — which would make a
  concurrency library's own test suite single-threaded, and hide exactly the races it should be
  finding — every test loads its models under a name generated by `unique_name/1`.

  Distinct names never collide in the registry, so the whole suite runs `async: true` against one
  running application, and the concurrency tests exercise real contention.

  ## What it provides

    * `unique_name/1` — a fresh model name per call
    * `load!/2` — load a model and block until ready, unloading it on exit
    * `attach_telemetry/1` — capture MLServe telemetry events as messages
    * `token/0` — a unique key for `MLServe.Test.Backends` call counters
    * `eventually/2` — poll an assertion instead of sleeping a fixed interval
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      import MLServe.Case

      alias MLServe.Test.Backends
    end
  end

  @doc """
  Returns a model name unique to this call.

  ## Examples

      name = unique_name()
      #=> :"model_512"
  """
  @spec unique_name(String.t()) :: atom()
  def unique_name(prefix \\ "model") do
    :"#{prefix}_#{System.unique_integer([:positive, :monotonic])}"
  end

  @doc "Returns a unique token for keying `MLServe.Test.Backends` counters."
  @spec token() :: reference()
  def token, do: make_ref()

  @doc """
  Writes a model artifact **inside the configured `:model_root`** and removes it on exit.

  Fixtures for path-validated loads have to live under the real model root: writing to
  `System.tmp_dir!/0` and pointing a model at it is correctly rejected as `:outside_root`, which
  would make the test look like a bug in `MLServe.Security` rather than in the test.

  Returns `{absolute_path, sha256_hex}`.
  """
  @spec model_fixture!(binary()) :: {String.t(), String.t()}
  def model_fixture!(contents \\ "weights") do
    root = MLServe.Config.model_root()
    File.mkdir_p!(root)
    path = Path.join(root, "fixture_#{System.unique_integer([:positive])}.bin")
    File.write!(path, contents)
    ExUnit.Callbacks.on_exit(fn -> File.rm(path) end)

    {:ok, digest} = MLServe.Security.digest(path, :sha256)
    {path, digest}
  end

  @doc """
  Loads a model, waits for it to become ready, and unloads it when the test exits.

  Raises if the model does not become ready, so a test never proceeds against a half-loaded
  model and fails somewhere less obvious.

  ## Parameters

    - `opts`: model options, as `MLServe.load_model/2`
    - `name`: optional explicit name; defaults to `unique_name/1`
  """
  @spec load!(keyword(), atom() | nil) :: atom()
  def load!(opts, name \\ nil) do
    name = name || unique_name()
    {:ok, _ref} = MLServe.load_model(name, opts)

    ExUnit.Callbacks.on_exit(fn ->
      for version <- versions(name) do
        MLServe.unload_model(name, version: version, timeout: 100)
      end
    end)

    # Generous: CI machines are slow and contended, and a flaky readiness wait would look like a
    # bug in the code under test rather than in the harness.
    case MLServe.await_ready(name, 10_000) do
      :ok ->
        name

      {:error, :timeout} ->
        raise "model #{inspect(name)} did not become ready: #{inspect(MLServe.model_status(name))}"
    end
  end

  @doc """
  Registers a model without waiting for it to become ready.

  For tests that assert on the `:loading` or `:failed` states.
  """
  @spec register!(keyword(), atom() | nil) :: atom()
  def register!(opts, name \\ nil) do
    name = name || unique_name()
    {:ok, _ref} = MLServe.load_model(name, opts)

    ExUnit.Callbacks.on_exit(fn ->
      for version <- versions(name) do
        MLServe.unload_model(name, version: version, timeout: 100)
      end
    end)

    name
  end

  @doc """
  Attaches handlers that forward telemetry events to the calling process.

  Returns the reference that tags each message. Uses `:telemetry_test.attach_event_handlers/2`,
  which ships with `:telemetry`.

  > #### Always match on the model name {: .warning}
  >
  > Telemetry handlers are **global**. A handler attached here fires for events emitted by *any*
  > process, including models belonging to other tests running concurrently — the `ref` does not
  > isolate them, because it identifies the handler, not the emitter.
  >
  > So every assertion must pattern-match the model name, never just the event and ref:
  >
  >     ref = attach_telemetry([[:ml_serve, :prediction, :stop]])
  >     MLServe.predict(name, 1)
  >     assert_receive {[:ml_serve, :prediction, :stop], ^ref, measurements, %{model: ^name}}
  >
  > `assert_telemetry/3` does this for you.
  """
  @spec attach_telemetry([[atom()]]) :: reference()
  def attach_telemetry(events \\ nil) do
    events = events || MLServe.Telemetry.events()
    ref = :telemetry_test.attach_event_handlers(self(), events)
    ExUnit.Callbacks.on_exit(fn -> :telemetry.detach(ref) end)
    ref
  end

  @doc """
  Receives the next telemetry `event` for `model`, discarding events from other tests' models.

  Returns `{measurements, metadata}`.
  """
  @spec assert_telemetry(reference(), [atom()], atom(), timeout()) :: {map(), map()}
  def assert_telemetry(ref, event, model, timeout \\ 500) do
    deadline = System.monotonic_time(:millisecond) + timeout
    do_assert_telemetry(ref, event, model, deadline)
  end

  defp do_assert_telemetry(ref, event, model, deadline) do
    remaining = max(deadline - System.monotonic_time(:millisecond), 0)

    receive do
      {^event, ^ref, measurements, %{model: ^model} = metadata} ->
        {measurements, metadata}

      {^event, ^ref, _measurements, _metadata} ->
        do_assert_telemetry(ref, event, model, deadline)
    after
      remaining ->
        raise ExUnit.AssertionError,
          message: "no #{inspect(event)} event for model #{inspect(model)} within the timeout"
    end
  end

  @doc """
  Polls `fun` until it returns a truthy value or `timeout` elapses, then returns it.

  Preferred over `Process.sleep/1` for anything asynchronous: it fails fast when the condition
  already holds and does not encode a guess about how slow CI is.
  """
  @spec eventually((-> term()), timeout()) :: term()
  def eventually(fun, timeout \\ 1_000) do
    deadline = System.monotonic_time(:millisecond) + timeout
    do_eventually(fun, deadline)
  end

  defp do_eventually(fun, deadline) do
    case fun.() do
      falsy when falsy in [nil, false] ->
        if System.monotonic_time(:millisecond) >= deadline do
          flunk_timeout()
        else
          Process.sleep(5)
          do_eventually(fun, deadline)
        end

      value ->
        value
    end
  end

  defp flunk_timeout do
    raise ExUnit.AssertionError, message: "eventually/2 timed out waiting for a truthy value"
  end

  defp versions(name) do
    case MLServe.versions(name) do
      {:ok, versions} -> versions
      {:error, _} -> []
    end
  end
end
